#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6034-webs
    bind *:80
    mode http
    balance roundrobin
    server 6034-web-01 50.19.132.93 check
    server 6034-web-02 3.80.102.45 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
